n_planned_routes: 200
n_actual_routes: 2000

merch_items:
  - Apple
  - Pear
  - Banana
  - Kiwi
  - Orange
  - Mandarin
  - Strawberry
  - Mango

cities:
  - Amsterdam
  - Rotterdam
  - The Hague
  - Utrecht
  - Delft
  - Eindhoven
  - Groningen
  - Tilburg

merch_len_sampler:
  low: 3
  high: 5

merch_sampler_map:
  low: 50
  high: 100

route_len_sampler:
  low: 3
  high: 5

merch_item_noise_map:
  low: -50
  high: 50

merch_len_noiser:
  low: -2
  high: 2

route_len_sampler_noise:
  low: -1
  high: 1
