n_planned_routes: 10
n_actual_routes: 1000

merch_items:
  - Apple
  - Pear
  - Banana
  - Kiwi
  - Orange
  - Mandarin
  - Strawberry
  - Mango
  - Pineapple
  - Watermelon
  - Grapefruit
  - Lemon
  - Lime
  - Raspberry
  - Blueberry
  - Cherry
  - Peach
  - Plum
  - Avocado
  - Coconut
  - Papaya
  - Pomegranate
  - Fig
  - Blackberry
  - Cranberry
  - Guava
  - Passion fruit
  - Dragon fruit
  - Lychee
  - Apricot
  - Raspberry Pi
  - Coffee mug
  - T-shirt
  - Hoodie
  - Phone case
  - Keychain
  - Poster
  - Sticker pack
  - Backpack
  - Notebook
  - Tote bag

cities:
  - Amsterdam
  - Rotterdam
  - The Hague
  - Utrecht
  - Delft
  - Eindhoven
  - Groningen
  - Tilburg
  - Alkmaar
  - Breda
  - Maastricht
  - Nijmegen
  - Haarlem
  - Leiden
  - Zwolle
  - Arnhem
  - Dordrecht
  - Amersfoort
  - Den Bosch
  - Enschede
  - Apeldoorn
  - Leeuwarden
  - Almere
  - Deventer
  - Gouda
  - Zaanstad
  - Hoorn
  - Middelburg
  - Vlissingen
  - Roermond
  - Venlo
  - Heerlen
  - Emmen
  - Amstelveen
  - Alphen aan den Rijn
  - Hengelo
  - Purmerend
  - Helmond
  - Schiedam
  - Sittard
  - Den Helder
  - Lelystad
  - Spijkenisse
  - Zaandam
  - Oss
  - Harderwijk
  - Hoofddorp
  - Vlaardingen

merch_len_sampler:
  low: 10
  high: 15

merch_sampler_map:
  low: 50
  high: 100

route_len_sampler:
  low: 4
  high: 15

merch_item_noise_map:
  low: -5
  high: 5

merch_len_noiser:
  low: -3
  high: 3

route_len_sampler_noise:
  low: -2
  high: 2
